### ISSUE TITLE
Mistake in frequency of updating seed

### ISSUE THREAD

**Issue by RogovYaroslav** [matheuss/google-translate-token#1]
Actually, a seed for the token aka TKK (thats defined in the html of Translate's page) updates every MINUTE, so you should get new one every 60 seconds. Here's some pretty bad, but working python code for testing:
``` python
import requests, re, time
for i in range(0,70):
 re.compile(r'eval\(\'\(\(function\(\)\{var a\\x3d(-?[0-9]+);var b\\x3d(-?[0-9]+);return (-?[0-9]+)').findall(requests.get('https://translate.google.com').text)
 time.sleep(1) 

```

**Comment by matheuss** [comment]
Hey man, take a look at this:
<img width="682" alt="screen shot 2016-07-05 at 10 24 54 am" src="https://cloud.githubusercontent.com/assets/4721750/16586224/19aac560-429b-11e6-855e-8fe12f4a1b6e.png">
The math changes, but the result is the same 😊 The result is updated each hour, (10:00, 11:00, etc).
