### ISSUE TITLE
google-translate-api support

### ISSUE THREAD

**Issue by sati-bodhi** [matheuss/google-translate-token#23]
In case anybody is keen to revive this project, [this repo](https://github.com/bregydoc/gtranslate) was able to generate the right tokens for google translate.

**Comment by ttys3** [comment]
> In case anybody is keen to revive this project, [this repo](https://github.com/bregydoc/gtranslate) was able to generate the right tokens for google translate.

oh no. that's the legacy api now.

we are discussing the new batch api.

**Comment by sati-bodhi** [comment]
Oh, I thought [google-translate-api](https://github.com/matheuss/google-translate-api/issues/130) came down because of this. 

Anyway, hope the new batch API can be up as well.

**Comment by ttys3** [comment]
please close and rename this issue.
to avoid false positive

**Comment by sati-bodhi** [comment]
renamed.
